# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'FlatChores' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for FlatChores
  pod 'Firebase/Core'
  pod 'Firebase/Firestore'
  pod 'Firebase/Database'
  pod 'Firebase/Auth'

  pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'

  pod 'RNScreens', :path => '../node_modules/react-native-screens'

  target 'FlatChoresTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'FlatChores-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for FlatChores-tvOS

  target 'FlatChores-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
