pod 'Firebase/Core', '~> 5.3.0'
# Uncomment the next line to define a global platform for your project
 platform :ios, '12.0'

target 'FlatChores' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
pod 'Firebase/Core'
pod 'Firebase/Auth'
pod 'Firebase/Database'
pod 'Firebase/Firestore'
  # Pods for FlatChores

  target 'FlatChoresTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'FlatChores-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for FlatChores-tvOS

  target 'FlatChores-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
